### ISSUE TITLE
AMD CPU failed to turn on the driver

### ISSUE THREAD

**Issue by X-Crack** [Air14/HyperHide#11]
My CPU is AMD 1950x and CPU virtualization is enabled, but the driver is always in the state of loading failure.

I System Ver: Microsoft Windows [Version 10.0.19043.1110]

I started the test mode of windows 10 with the following command to allow unsigned driver loading options.

The driver could not be loaded

```
bcdedit.exe /set nointegritychecks on 
bcdedit.exe /set loadoptions DDISABLE_INTEGRITY_CHECKS
bcdedit.exe /set testsigning on
```

error:
C:\Windows\system32>sc start airhv
[SC] StartService fail 2:
C:\Windows\system32>sc start HyperHideDrv
[SC] StartService fail 31:

![20210731001035](https://user-images.githubusercontent.com/45416520/127681287-804dd676-9338-4ce5-ad7b-f57505fe6d8d.png)

**Comment by Air14** [comment]
HyperHide currently support only intel processors
