### ISSUE TITLE
Issue Starting Drivers

### ISSUE THREAD

**Issue by MoneyWasted** [Air14/HyperHide#14]
I've tried multiple times and nothing seems to work. Any suggestions.
![Image](https://user-images.githubusercontent.com/45946092/132077749-a9465c10-0d13-4060-a405-0cea3ba7be93.PNG)

**Comment by Air14** [comment]
Did you put these drivers to binpath which you specified? And secondly you can use Dbgview form sysinternals suite to check error messages, be sure to have checked these options
![Dbgview](https://user-images.githubusercontent.com/34422030/132096809-b34eed50-bdc0-4850-840c-25f13c1cca29.png)

**Comment by Air14** [comment]
Closed due to no response

**Comment by MoneyWasted** [comment]
Oh shit I complete forgot I had this open. I do have an AMD CPU if that's the reason it wasn't working.
