### ISSUE TITLE
vmp3.5 "Virtual Machine"

### ISSUE THREAD

**Issue by nblog** [Air14/HyperHide#16]
![image](https://user-images.githubusercontent.com/10218627/134282190-bf63500c-a492-4fbd-8fa4-7d9ce8faef71.png)

vmprotect v3.5.0,
any program will prompt as long as virtual machine detection is enabled.
HyperHide->(√)Hypervisor not visible

**Comment by Air14** [comment]
vmprotect uses rdtsc time attacks which my hv is vulnerable to. And "Hypervisor not visible" option just tells hv to don't expose itself via cpuid

**Comment by nblog** [comment]
uses "eflags exception" + "seh" check


![image](https://user-images.githubusercontent.com/10218627/135216883-8746426e-281d-4446-bfc8-93d33707d5df.png)

[Test Examples.zip](https://github.com/Air14/HyperHide/files/7249463/Test.Examples.zip)
