### ISSUE TITLE
HookedNtYieldExecution return value error

### ISSUE THREAD

**Issue by taodaqiao** [Air14/HyperHide#19]
if(Hider::IsHidden(IoGetCurrentProcess(), HIDE_NT_YIELD_EXECUTION) == TRUE)
	{
		OriginalNtYieldExecution();
		return STATUS_SUCCESS; //return here STATUS_NO_YIELD_PERFORMED
	}

**Comment by Air14** [comment]
To be honest, this is irrelevant, because in a non-debugged application NtYieldExecution returns STATUS_SUCCESS as often as STATUS_NO_YIELD_PERFORMED
