### ISSUE TITLE
was detected

### ISSUE THREAD

**Issue by ansely** [Air14/HyperHide#21]
detected as a virtual machine

**Comment by Air14** [comment]
Can you specify what you mean by "detected as a virtual machine" ?

**Comment by Air14** [comment]
Closed due to no response

**Comment by youhongyouzhuan** [comment]
> Can you specify what you mean by "detected as a virtual machine" ?您能否具体说明一下“检测到为虚拟机”是什么意思？

他可能在调试游戏，游戏检测到了你开启了VT 认为自己处于虚拟环境中。多见ACE反作弊游戏。
