### ISSUE TITLE
Error while opening on.bat Winver 21h2

### ISSUE THREAD

**Issue by RCE892** [Air14/HyperHide#23]
![image](https://user-images.githubusercontent.com/110685735/183774109-3c26271e-31e1-49c4-a5a4-fab2d9eef76d.png)

**Comment by Air14** [comment]
Could you please send me result of this command 'sc qc airhv' ?

**Comment by RCE892** [comment]
![image](https://user-images.githubusercontent.com/110685735/187765061-d19133a4-5a2b-49a2-9428-96bec22bc93d.png)

**Comment by RCE892** [comment]
sorry for late reply i will now reply quicker

**Comment by RCE892** [comment]
![image](https://user-images.githubusercontent.com/110685735/187765462-ae8f4d0c-cf54-459a-b1e7-3bf06086a17d.png)

**Comment by Air14** [comment]
Do you have intel processor with VT-x support?

**Comment by RCE892** [comment]
> Do you have intel processor with VT-x support?

i have amd proccessor

**Comment by RCE892** [comment]
> 

also heres a picture of my system info 
![image](https://user-images.githubusercontent.com/110685735/187779418-65af9715-e396-4219-b57f-337192b9f77c.png)

**Comment by Air14** [comment]
Unfortunately hyperhide supports only intel processors

**Comment by RCE892** [comment]
> Unfortunately hyperhide supports only intel processors

Noooo :( Will you support amd cpus ❤️

**Comment by Air14** [comment]
I don't have an amd processor so I'm not able to create a hypervisor for it
