### ISSUE TITLE
not work with VMProtect 3.6

### ISSUE THREAD

**Issue by jmloli88** [Air14/HyperHide#28]
VMProtect 3.6 is detecting hyperhide in x64dgb. May be this can be implemented

https://blog.csdn.net/qq_37353105/article/details/125482851

**Comment by Air14** [comment]
Could you send me a protected binary that detects hyperhide? Because I have a binary protected by VMProtect 3.6 but nothing is detected

**Comment by Air14** [comment]
fixed in https://github.com/Air14/HyperHide/commit/55ab75cc2a99301b0b3c81c459a2a4fc2a8e4500

**Comment by Ahora57** [comment]
We continue to insert code from WRK/other anti-anti-debug plugin and do not analyze the work of functions? :)
