### ISSUE TITLE
[SC] StartService FAILED 31:  12th Gen Intel(R) Core(TM) i7-12700KF 22H2

### ISSUE THREAD

**Issue by shadow0x000** [Air14/HyperHide#29]
[SC] StartService FAILED 31:  12th Gen Intel(R) Core(TM) i7-12700KF 22H2

<img width="1697" alt="微信截图_20221229000230" src="https://user-images.githubusercontent.com/20574312/209839451-1bce2610-aef0-4d10-a46a-df410f1393b6.png">

**Comment by Air14** [comment]
Fixed in https://github.com/Air14/HyperHide/commit/0042fe8420adbe54150b376e5aa55dd34dc87482
