### ISSUE TITLE
Compile failed （win7 x64 6.1.7601.24441）

### ISSUE THREAD

**Issue by fullxu** [Air14/HyperHide#5]
When i try to compile the latest code, i got  a lot of errors, can someone tell me how to fix? thanks for a lot.

![捕获](https://user-images.githubusercontent.com/11195717/123357554-4d188880-d59c-11eb-8a66-20af7d6fac5b.PNG)

Details:
Windows 7 x64 sp1 ( 6.1.7601.24441)
Microsoft Visual Studio Enterprise 2019 version 16.10.2
WDK 10.0.19030.1000

**Comment by acheron2302** [comment]
Can i ask how did u solve this problem?
