### ISSUE TITLE
Request for new features - CPUID - RDTSC

### ISSUE THREAD

**Issue by UnlimitedChild** [Air14/HyperHide#6]
Hi, 

some features, CPUID and RDTSC Hooking, are missing in this plugin. 

Best regards

**Comment by Air14** [comment]
Rdtsc is in my opinion too sensitive to hook so this feature probably won't be implemented. Also what information would you want to hide with cpuid hooking?

**Comment by UnlimitedChild** [comment]
Modern security tools use these methods to detect program debugging. CPUID is used to bind the program execution environment and to perform antidump protection.
[hypervisor_example_rdtsc-master.zip](https://github.com/Air14/HyperHide/files/6758495/hypervisor_example_rdtsc-master.zip)

**Comment by nblog** [comment]
'CPUID' can detect vm, It will detect the Hypervisor, for this type, it will be treated as a virtual machine environment.

**Comment by UnlimitedChild** [comment]
Detecting VMs using the CPUID instruction - https://github.com/ioncodes/is-vm/blob/master/vm.asm

**Comment by UnlimitedChild** [comment]
> 'CPUID' can detect vm, It will detect the Hypervisor, for this type, it will be treated as a virtual machine environment.

Does this plugin have nested virtualization support ?!

**Comment by Air14** [comment]
> > 'CPUID' can detect vm, It will detect the Hypervisor, for this type, it will be treated as a virtual machine environment.
> 
> Does this plugin have nested virtualization support ?!

No, it doesn't have

**Comment by Air14** [comment]
Added new feature in [HyperHide_2021-07-19](https://github.com/Air14/HyperHide/releases/tag/HyperHide_2021-07-19) which allow to hide presence of hypervisor (only cpuid, rdtsc/rdtscp still not supported)
